# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-05 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=5)),
                ('group_name', models.CharField(max_length=150)),
                ('desc', models.CharField(max_length=1000)),
                ('works_type', models.CharField(max_length=150, null=True)),
                ('works_tag', models.CharField(max_length=150, null=True)),
                ('image', models.ImageField(default=None, null=True, upload_to='photos')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('desc', models.CharField(max_length=3000)),
                ('event_date', models.CharField(max_length=20)),
                ('image', models.ImageField(default=None, null=True, upload_to='photos')),
            ],
        ),
        migrations.AddField(
            model_name='booth',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Event'),
        ),
    ]
