# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-05 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booth',
            name='desc',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='booth',
            name='group_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='booth',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='booth',
            name='number',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='booth',
            name='works_tag',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='booth',
            name='works_type',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
