# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-12 06:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('map', '0003_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Favorite_Booth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booth', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='map.Booth')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='favorite_booth',
        ),
        migrations.AddField(
            model_name='event',
            name='event_address',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
