# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-19 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_auto_20190519_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booth',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
