# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-21 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import map.models
import map.storage


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_auto_20190519_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booth',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, storage=map.storage.OverwriteStorage(), upload_to=map.models.Booth_file_name),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default=None, null=True, storage=map.storage.OverwriteStorage(), upload_to=map.models.Event_file_name),
        ),
    ]
