# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-25 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_auto_20190521_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='booth',
            name='url',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
