# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-25 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_booth_url'),
        ('map', '0009_auto_20190525_2056'),
    ]

    operations = [
    ]
